--
-- PostgreSQL database dump
--

-- Dumped from database version 11.5
-- Dumped by pg_dump version 12.1

-- Started on 2020-08-02 16:08:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 45989)
-- Name: default; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA "default";


ALTER SCHEMA "default" OWNER TO postgres;

SET default_tablespace = '';

--
-- TOC entry 207 (class 1259 OID 46063)
-- Name: account; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".account (
    id bigint NOT NULL,
    owner bigint NOT NULL,
    name character varying NOT NULL,
    created_on timestamp without time zone,
    updated_on timestamp without time zone,
    author_id bigint NOT NULL,
    updated_by bigint,
    external_id character varying
);


ALTER TABLE "default".account OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 70564)
-- Name: account_id_seq; Type: SEQUENCE; Schema: default; Owner: postgres
--

ALTER TABLE "default".account ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "default".account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 54201)
-- Name: departments; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".departments (
    id bigint NOT NULL,
    name character varying NOT NULL,
    code character varying NOT NULL,
    office_id bigint NOT NULL,
    parent_department bigint
);


ALTER TABLE "default".departments OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 54217)
-- Name: employee_station; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".employee_station (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    office_id bigint NOT NULL,
    station_id bigint
);


ALTER TABLE "default".employee_station OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 54209)
-- Name: employees; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".employees (
    id bigint NOT NULL,
    names character varying,
    gender character varying,
    created_on timestamp without time zone,
    updated_on timestamp without time zone,
    author_id bigint,
    updated_by bigint
);


ALTER TABLE "default".employees OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 54180)
-- Name: kiosks; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".kiosks (
    id bigint NOT NULL,
    reference character varying NOT NULL,
    details character varying,
    device_token character varying,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    author_id bigint,
    udated_by bigint,
    station_id bigint
);


ALTER TABLE "default".kiosks OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 54196)
-- Name: office_station; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".office_station (
    id bigint NOT NULL,
    office_id bigint NOT NULL,
    station_id bigint
);


ALTER TABLE "default".office_station OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 54188)
-- Name: offices; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".offices (
    id bigint NOT NULL,
    name character varying NOT NULL,
    dateopened date NOT NULL,
    parent_office bigint,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    author_id bigint,
    updated_by bigint
);


ALTER TABLE "default".offices OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 46050)
-- Name: permission_scope; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".permission_scope (
    id bigint NOT NULL,
    key character varying,
    value character varying
);


ALTER TABLE "default".permission_scope OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 46027)
-- Name: permissions; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".permissions (
    id bigint NOT NULL,
    code character varying,
    name character varying,
    "grouping" character varying
);


ALTER TABLE "default".permissions OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 46025)
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: default; Owner: postgres
--

ALTER TABLE "default".permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "default".permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 62373)
-- Name: profile; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".profile (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    firstname character varying,
    lastname character varying,
    author_id bigint,
    created_on time without time zone NOT NULL,
    updated_by bigint,
    dateupdated timestamp without time zone
);


ALTER TABLE "default".profile OWNER TO postgres;

--
-- TOC entry 199 (class 1259 OID 46000)
-- Name: role; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".role (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    is_system boolean NOT NULL,
    created_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_on timestamp without time zone,
    author_id bigint,
    updated_by bigint
);


ALTER TABLE "default".role OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 45998)
-- Name: role_id_seq; Type: SEQUENCE; Schema: default; Owner: postgres
--

ALTER TABLE "default".role ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "default".role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 46035)
-- Name: role_permission; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".role_permission (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    author_id bigint,
    updated_by bigint,
    scope_id bigint
);


ALTER TABLE "default".role_permission OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 46086)
-- Name: stations; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".stations (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    name character varying,
    code character varying
);


ALTER TABLE "default".stations OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 46010)
-- Name: user_role; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".user_role (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    status character varying(50) NOT NULL,
    author_id bigint,
    created_on timestamp without time zone,
    updated_on timestamp without time zone,
    updated_by bigint
);


ALTER TABLE "default".user_role OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 46008)
-- Name: user_role_id_seq; Type: SEQUENCE; Schema: default; Owner: postgres
--

ALTER TABLE "default".user_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "default".user_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 197 (class 1259 OID 45990)
-- Name: users; Type: TABLE; Schema: default; Owner: postgres
--

CREATE TABLE "default".users (
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    author_id bigint,
    created_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_on timestamp without time zone,
    updated_by bigint
);


ALTER TABLE "default".users OWNER TO postgres;

--
-- TOC entry 2946 (class 0 OID 0)
-- Dependencies: 197
-- Name: TABLE users; Type: COMMENT; Schema: default; Owner: postgres
--

COMMENT ON TABLE "default".users IS 'Manage Users';


--
-- TOC entry 200 (class 1259 OID 46006)
-- Name: users_id_seq; Type: SEQUENCE; Schema: default; Owner: postgres
--

ALTER TABLE "default".users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "default".users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2931 (class 0 OID 46063)
-- Dependencies: 207
-- Data for Name: account; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".account (id, owner, name, created_on, updated_on, author_id, updated_by, external_id) FROM stdin;
2	6	Kode Inc	\N	\N	6	\N	Stream(i, ?)
\.


--
-- TOC entry 2936 (class 0 OID 54201)
-- Dependencies: 212
-- Data for Name: departments; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".departments (id, name, code, office_id, parent_department) FROM stdin;
\.


--
-- TOC entry 2938 (class 0 OID 54217)
-- Dependencies: 214
-- Data for Name: employee_station; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".employee_station (id, employee_id, office_id, station_id) FROM stdin;
\.


--
-- TOC entry 2937 (class 0 OID 54209)
-- Dependencies: 213
-- Data for Name: employees; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".employees (id, names, gender, created_on, updated_on, author_id, updated_by) FROM stdin;
\.


--
-- TOC entry 2933 (class 0 OID 54180)
-- Dependencies: 209
-- Data for Name: kiosks; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".kiosks (id, reference, details, device_token, created_on, updated_on, author_id, udated_by, station_id) FROM stdin;
\.


--
-- TOC entry 2935 (class 0 OID 54196)
-- Dependencies: 211
-- Data for Name: office_station; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".office_station (id, office_id, station_id) FROM stdin;
\.


--
-- TOC entry 2934 (class 0 OID 54188)
-- Dependencies: 210
-- Data for Name: offices; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".offices (id, name, dateopened, parent_office, created_on, updated_on, author_id, updated_by) FROM stdin;
\.


--
-- TOC entry 2930 (class 0 OID 46050)
-- Dependencies: 206
-- Data for Name: permission_scope; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".permission_scope (id, key, value) FROM stdin;
\.


--
-- TOC entry 2928 (class 0 OID 46027)
-- Dependencies: 204
-- Data for Name: permissions; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".permissions (id, code, name, "grouping") FROM stdin;
\.


--
-- TOC entry 2939 (class 0 OID 62373)
-- Dependencies: 215
-- Data for Name: profile; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".profile (id, user_id, firstname, lastname, author_id, created_on, updated_by, dateupdated) FROM stdin;
\.


--
-- TOC entry 2923 (class 0 OID 46000)
-- Dependencies: 199
-- Data for Name: role; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".role (id, code, name, is_system, created_on, updated_on, author_id, updated_by) FROM stdin;
2	OWNER	ACCOUNT_OWNER	t	2020-07-17 02:05:36.156864	\N	\N	\N
\.


--
-- TOC entry 2929 (class 0 OID 46035)
-- Dependencies: 205
-- Data for Name: role_permission; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".role_permission (id, role_id, permission_id, created_on, updated_on, author_id, updated_by, scope_id) FROM stdin;
\.


--
-- TOC entry 2932 (class 0 OID 46086)
-- Dependencies: 208
-- Data for Name: stations; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".stations (id, account_id, name, code) FROM stdin;
\.


--
-- TOC entry 2926 (class 0 OID 46010)
-- Dependencies: 202
-- Data for Name: user_role; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".user_role (id, user_id, role_id, status, author_id, created_on, updated_on, updated_by) FROM stdin;
4	2	2	active	\N	\N	\N	\N
\.


--
-- TOC entry 2921 (class 0 OID 45990)
-- Dependencies: 197
-- Data for Name: users; Type: TABLE DATA; Schema: default; Owner: postgres
--

COPY "default".users (id, username, password, author_id, created_on, updated_on, updated_by) FROM stdin;
2	moverr@gmail.com	password	\N	2020-07-17 01:12:52.306489	\N	\N
3	mosverr@gmail.com	password	\N	2020-07-29 03:06:28.087261	\N	\N
4	m7sverr@gmail.com	password	\N	2020-07-29 03:08:54.05777	\N	\N
5	m7svserr@gmail.com	password	\N	2020-07-29 03:12:13.794758	\N	\N
6	ninja@gmail.com	5e884898da2807151d0e56f8dc6292773603d06aabbdd62a11ef721d1542d8	\N	2020-07-29 03:30:28.772393	\N	\N
7	nijar@gmail.com	5e884898da2807151d0e56f8dc6292773603d06aabbdd62a11ef721d1542d8	\N	2020-07-29 18:25:17.237882	\N	\N
8	anijar@gmail.com	5e884898da2807151d0e56f8dc6292773603d06aabbdd62a11ef721d1542d8	\N	2020-07-29 19:06:37.404634	\N	\N
\.


--
-- TOC entry 2947 (class 0 OID 0)
-- Dependencies: 216
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: default; Owner: postgres
--

SELECT pg_catalog.setval('"default".account_id_seq', 2, true);


--
-- TOC entry 2948 (class 0 OID 0)
-- Dependencies: 203
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: default; Owner: postgres
--

SELECT pg_catalog.setval('"default".permissions_id_seq', 1, false);


--
-- TOC entry 2949 (class 0 OID 0)
-- Dependencies: 198
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: default; Owner: postgres
--

SELECT pg_catalog.setval('"default".role_id_seq', 2, true);


--
-- TOC entry 2950 (class 0 OID 0)
-- Dependencies: 201
-- Name: user_role_id_seq; Type: SEQUENCE SET; Schema: default; Owner: postgres
--

SELECT pg_catalog.setval('"default".user_role_id_seq', 4, true);


--
-- TOC entry 2951 (class 0 OID 0)
-- Dependencies: 200
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: default; Owner: postgres
--

SELECT pg_catalog.setval('"default".users_id_seq', 8, true);


--
-- TOC entry 2775 (class 2606 OID 46070)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 2785 (class 2606 OID 54208)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- TOC entry 2789 (class 2606 OID 54221)
-- Name: employee_station employee_station_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".employee_station
    ADD CONSTRAINT employee_station_pkey PRIMARY KEY (id);


--
-- TOC entry 2787 (class 2606 OID 54216)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- TOC entry 2779 (class 2606 OID 54187)
-- Name: kiosks kiosks_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".kiosks
    ADD CONSTRAINT kiosks_pkey PRIMARY KEY (id);


--
-- TOC entry 2783 (class 2606 OID 54200)
-- Name: office_station office_station_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".office_station
    ADD CONSTRAINT office_station_pkey PRIMARY KEY (id);


--
-- TOC entry 2781 (class 2606 OID 54195)
-- Name: offices offices_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".offices
    ADD CONSTRAINT offices_pkey PRIMARY KEY (id);


--
-- TOC entry 2773 (class 2606 OID 46057)
-- Name: permission_scope permission_scope_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".permission_scope
    ADD CONSTRAINT permission_scope_pkey PRIMARY KEY (id);


--
-- TOC entry 2769 (class 2606 OID 46034)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 2791 (class 2606 OID 62380)
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- TOC entry 2771 (class 2606 OID 46039)
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 2765 (class 2606 OID 46005)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 2777 (class 2606 OID 46093)
-- Name: stations stations_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".stations
    ADD CONSTRAINT stations_pkey PRIMARY KEY (id);


--
-- TOC entry 2767 (class 2606 OID 46014)
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);


--
-- TOC entry 2763 (class 2606 OID 45997)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2798 (class 2606 OID 46076)
-- Name: account author_id; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".account
    ADD CONSTRAINT author_id FOREIGN KEY (author_id) REFERENCES "default".users(id) NOT VALID;


--
-- TOC entry 2797 (class 2606 OID 46071)
-- Name: account owner; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".account
    ADD CONSTRAINT owner FOREIGN KEY (owner) REFERENCES "default".users(id);


--
-- TOC entry 2795 (class 2606 OID 46045)
-- Name: role_permission permission_id; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".role_permission
    ADD CONSTRAINT permission_id FOREIGN KEY (permission_id) REFERENCES "default".permissions(id) NOT VALID;


--
-- TOC entry 2793 (class 2606 OID 46020)
-- Name: user_role role; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".user_role
    ADD CONSTRAINT role FOREIGN KEY (role_id) REFERENCES "default".role(id) NOT VALID;


--
-- TOC entry 2794 (class 2606 OID 46040)
-- Name: role_permission role_id; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".role_permission
    ADD CONSTRAINT role_id FOREIGN KEY (role_id) REFERENCES "default".role(id) NOT VALID;


--
-- TOC entry 2796 (class 2606 OID 46058)
-- Name: role_permission scope_id; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".role_permission
    ADD CONSTRAINT scope_id FOREIGN KEY (scope_id) REFERENCES "default".permission_scope(id) NOT VALID;


--
-- TOC entry 2799 (class 2606 OID 46081)
-- Name: account updated_by; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".account
    ADD CONSTRAINT updated_by FOREIGN KEY (updated_by) REFERENCES "default".users(id) NOT VALID;


--
-- TOC entry 2792 (class 2606 OID 46015)
-- Name: user_role user; Type: FK CONSTRAINT; Schema: default; Owner: postgres
--

ALTER TABLE ONLY "default".user_role
    ADD CONSTRAINT "user" FOREIGN KEY (user_id) REFERENCES "default".users(id) NOT VALID;


-- Completed on 2020-08-02 16:08:33

--
-- PostgreSQL database dump complete
--

